/* 
 * Release Manager
 *
 * This application generate version for your software.
 *
 * OpenAPI spec version: 0.2.0
 * Contact: vitalleshchyk@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct VersionIncrementalApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> VersionIncrementalApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> VersionIncrementalApiClient<C> {
        VersionIncrementalApiClient {
            configuration: configuration,
        }
    }
}

pub trait VersionIncrementalApi {
    fn incremental_delete(&self, project_name: &str) -> Box<Future<Item = (), Error = Error>>;
    fn incremental_generate(&self, project_name: &str) -> Box<Future<Item = ::models::IncrementalVersionNumber, Error = Error>>;
    fn incremental_update(&self, project_name: &str, body: ::models::IncrementalVersionNumber) -> Box<Future<Item = ::models::IncrementalVersionNumber, Error = Error>>;
}


impl<C: hyper::client::Connect>VersionIncrementalApi for VersionIncrementalApiClient<C> {
    fn incremental_delete(&self, project_name: &str) -> Box<Future<Item = (), Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Delete;

        let uri_str = format!("{}/increamental_version/{projectName}", configuration.base_path, projectName=project_name);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|_| futures::future::ok(()))
        )
    }

    fn incremental_generate(&self, project_name: &str) -> Box<Future<Item = ::models::IncrementalVersionNumber, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Post;

        let uri_str = format!("{}/increamental_version/{projectName}", configuration.base_path, projectName=project_name);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());



        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::IncrementalVersionNumber, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn incremental_update(&self, project_name: &str, body: ::models::IncrementalVersionNumber) -> Box<Future<Item = ::models::IncrementalVersionNumber, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Put;

        let uri_str = format!("{}/increamental_version/{projectName}", configuration.base_path, projectName=project_name);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());


        let serialized = serde_json::to_string(&body).unwrap();
        req.headers_mut().set(hyper::header::ContentType::json());
        req.headers_mut().set(hyper::header::ContentLength(serialized.len() as u64));
        req.set_body(serialized);

        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::IncrementalVersionNumber, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
